version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: yarn start
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data:
